### ISSUE TITLE
v1beta1 planning

### ISSUE THREAD

**Issue by ffromani** [k8stopologyawareschedwg/noderesourcetopology-api#21]
proposed changes for `v1beta1`, to be discussed

1. move fields under `status` - NRT describes the status of resources on a node, so it makes sense to honor the spec/status split and to have the fields reported as status
2. add constants for values we use repeatedly, like "Node" (and possibly more). Also add constants for max supported NUMA zones (64)
3. evaluate addition of golang helpers, e.g. to extract the zone ID from the name
4. ~make topologyPolicy a single string~
5. ~report TM scope alongside policy~
6. ~a more radical approach: split the TM configuration data into a new object~
7. remove topologyPolicy entirely. Document how node-local Topology Manager configuration can be expressed (~labels~ use top-level attributes added in v1alpha2)
8. ~podfingerprint as value~ (from annotation: use top-level attributes added in v1alpha2)
9. fix short name: move from `node-res-topo` to  `nrt`
10. rename package name (https://github.com/k8stopologyawareschedwg/noderesourcetopology-api/issues/20)
11. change zonelist? (https://github.com/k8stopologyawareschedwg/noderesourcetopology-api/pull/17)

**Comment by ffromani** [comment]
quick demo:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2022-04-21T11:30:27Z"
  name: noderesourcetopologies.topology.node.k8s.io
spec:
  conversion:
    strategy: None
  group: topology.node.k8s.io
  names:
    kind: NodeResourceTopology
    listKind: NodeResourceTopologyList
    plural: noderesourcetopologies
    shortNames:
      - nrt
    singular: noderesourcetopology
  scope: Cluster
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          description: NodeResourceTopology describes node resources and their topology.
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            status:
              description: NodeResourceTopologyStatus defines the observed state of NodeResourceTopology
              zones:
                description: ZoneList contains an array of Zone objects.
                items:
                  description: Zone represents a resource topology zone, e.g. socket, node, die or core.
                  properties:
                    attributes:
                      description: AttributeList contains an array of AttributeInfo objects.
                      items:
                        description: AttributeInfo contains one attribute of a Zone.
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                        required:
                          - name
                          - value
                        type: object
                      type: array
                    costs:
                      description: CostList contains an array of CostInfo objects.
                      items:
                        description: CostInfo describes the cost (or distance) between two Zones.
                        properties:
                          name:
                            type: string
                          value:
                            format: int64
                            type: integer
                        required:
                          - name
                          - value
                        type: object
                      type: array
                    name:
                      type: string
                    parent:
                      type: string
                    resources:
                      description: ResourceInfoList contains an array of ResourceInfo objects.
                      items:
                        description: ResourceInfo contains information about one resource type.
                        properties:
                          allocatable:
                            anyOf:
                              - type: integer
                              - type: string
                            description: Allocatable quantity of the resource, corresponding to allocatable in node status, i.e. total amount of this resource available to be used by pods.
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          available:
                            anyOf:
                              - type: integer
                              - type: string
                            description: Available is the amount of this resource currently available for new (to be scheduled) pods, i.e. Allocatable minus the resources reserved by currently running pods.
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          capacity:
                            anyOf:
                              - type: integer
                              - type: string
                            description: Capacity of the resource, corresponding to capacity in node status, i.e. total amount of this resource that the node has.
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          name:
                            description: Name of the resource.
                            type: string
                        required:
                          - allocatable
                          - available
                          - capacity
                          - name
                        type: object
                      type: array
                    type:
                      type: string
                  required:
                    - name
                    - type
                  type: object
                type: array
              type: object
          required:
            - zones
          type: object
      served: true
      storage: true
```
